# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "W", "B","N", "C90", "I", "ASYNC", "S", "BLE", "A", "COM", "C4", "DTZ", "DJ", "PYI", "RET", "SIM", "ARG", "PL"]

# Never enforce `E501` (line length violations).
ignore = ["N999"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = []

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[per-file-ignores]
"__init__.py" = ["E402"]
