name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Markdown linter
        run: Stub

      - name: Run linter
        run: echo Stub

      - name: Run tests
        run: echo Stub
