name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  CheckTheIssueNumber:
    runs-on: ubuntu-lates
    steps:
      - name: Check PR title to be correct
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "^#[0-9]+:.+"
          flags: g

  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Markdown linter
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: '**/*.md'

      - name: Run Python Linter
        uses: jpetrucciani/ruff-check@main

  UnitTesting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: [barny-agent, barny-server]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install required dependencies
        run: pip3 install -r ${{ matrix.projects }}/requirements.txt

      - name: Run tests
        run: python3 -m unittest discover ${{ matrix.projects }}
