name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Markdown linter
        run: echo Stub
  

  UnitTesting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: [barny-agent, barny-server]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install required dependencies
        run: pip3 -r ${{ matrix.projects }}/requirements.txt

      - name: Run Python linter
        run: echo Stub for ${{ matrix.projects }}

      - name: Run tests
        run: python3 -m unittest discover ${{ matrix.projects }}
